name: CI básico
# Eventos que activan el workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # También se puede ejecutar manualmente desde la interfaz de GitHub
  workflow_dispatch:
# Trabajos que ejecutará este workflow
jobs:
  # Un trabajo llamado "build"
  build:
    # Se ejecutará en la última versión de Ubuntu
    runs-on: ubuntu-latest
    # Pasos del trabajo
    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v3
      # Paso 2: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'          
      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: npm ci        
      # Paso 4: Ejecutar pruebas
      - name: Ejecutar pruebas
        run: npm test        
      # Paso 5: Construir la aplicación
      - name: Construir proyecto
        run: npm run build
